//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveBindingDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveBindingDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a PointBinder, edit the BindingGroups collection, &quot;Add&quot; a new binding group, and set its AutoGet property to True. 
        ///
        ///On a TextBox, use &quot;Bind to Point&quot; command and select the OPC item and property you want to get. Then, use the &quot;Edit Live Bindings&quot; command, and set the BindingGroup property of the property binding to the binding group you have created earlier. The Read (in this case, a Get) operation is automatically executed for all property bindings in this group when the form loads..
        /// </summary>
        internal static string Form1_automaticGetLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_automaticGetLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a PointBinder, edit the BindingGroups collection, &quot;Add&quot; a new binding group, set its AutoRead property to True, and make sure that its AutoSubscribe property is set to False. 
        ///
        ///On a TextBox, use &quot;Bind to Point&quot; command and select the OPC item you want to read. Then, use the &quot;Edit Live Bindings&quot; command, and set the BindingGroup property of the item binding to the binding group you have created earlier. The Read operation is automatically executed for all item bindings in this group when the form loads..
        /// </summary>
        internal static string Form1_automaticReadLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_automaticReadLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have not done so yet, drag the DAConnectivity component from the Toolbox to the form (this is a common step for all binding tasks). 
        ///
        ///Use the &quot;Bind to Point&quot; command on the target control, and select the source OPC server and OPC item. 
        ///
        ///That&apos;s it. You can verify the result immediately, without recompiling your application, by using the &quot;Design Online&quot; command on the BindingExtender component..
        /// </summary>
        internal static string Form1_automaticSubscriptionLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_automaticSubscriptionLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind the OPC item to your control as usually. 
        ///
        ///Then, use the &quot;Edit Live Bindings&quot; command on the control, and for the ArgumentsPath property, select the argument you want. .
        /// </summary>
        internal static string Form1_bindingKindsLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_bindingKindsLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the StatusToColorConverter component from the toolbox to the form. Bind the OPC item to your control as usually. 
        ///
        ///Then, use the &quot;Edit Live Bindings&quot; command, &quot;Clone&quot; the existing binding, and change the cloned binding as follows: Set the ArgumentsPath to StatusInfo. Set the ValueTarget.TargetMember to the BackColor (or other suitable) property of your control, and for the Converter property, select the StatusToColorConverter you have placed to the form earlier. This will cause the status information f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form1_changeBackgroundLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_changeBackgroundLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a PointBinder, edit the BindingGroups collection, &quot;Add&quot; a new binding group, set its AutoSubscribe property to False, and set its WriteEventSource.SourceComponent to the button that should invoke the Write. 
        ///
        ///Drag the ErrorProvider extender (standard Microsoft component) from the toolbox to the form. 
        ///Configure the binding in a usual way. Use the &quot;Edit Live Bindings&quot; command, and for the BindingOperations options, select only &quot;Write&quot;, and set the BindingGroup property of the item binding to the binding g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form1_displayWriteErrorsLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_displayWriteErrorsLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the ErrorProvider extender (standard Microsoft component) from the toolbox to the form. Configure the binding in a usual way. 
        ///
        ///Then, use the &quot;Edit Live Bindings&quot; command, &quot;Clone&quot; the existing binding, and change the cloned binding as follows: Set the ArgumentsPath to ErrorMessage. Set the ValueTarget.ExtenderProvider to the ErrorProvider component on your form, and set the ValueTarget.TargetMember to the Error member. All in all, this will cause the error message from the OPC item be stored into the e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form1_errorProviderLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_errorProviderLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the ToolTip extender (standard Microsoft component), or other extender provider you need, from the toolbox to the form. Configure the binding in a usual way. 
        ///Then, use the &quot;Edit Live Bindings&quot; command, &quot;Clone&quot; the existing binding, and change the cloned binding as follows: Set the ValueTarget.ExtenderProvider to the ToolTip (extender provider) component on your form, and set the ValueTarget.TargetMember to the Tooltip member. Set the ArgumentsPath to Vtq (or Timestamp, Quality, or whatever you&apos;ll want [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form1_extendersLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_extendersLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a TextBox, use &quot;Bind to Point&quot; command and select the OPC item and property you want to get (alternatively, use  &quot;Edit Live Bindings&quot; command, &quot;Add&quot; a PointBinding, and configure its ServerDescriptor and PropertyDescriptor). 
        ///
        ///In order to have the Read (property Get) invoked when the button is pressed, set the ReadEventSource.SourceComponent to the Button control; the SourceMember of the ReadEventSource will be automatically set to the Click event. This causes the Click on the button execute the Read (pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form1_getOnEventLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_getOnEventLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a TextBox, use &quot;Bind to Point&quot; command and select the OPC item you want to read (alternatively, use  &quot;Edit Live Bindings&quot; command, &quot;Add&quot; a PointBinding, and configure its ServerDescriptor and ItemDescriptor). 
        ///
        ///Then, use the &quot;Edit Live Bindings&quot; command, and for BindingOperations property, leave just Read checked (and uncheck the Subscribe). In order to have the Read invoked when the button is pressed, set the ReadEventSource.SourceComponent to the Button control; the SourceMember of the ReadEventSource  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form1_readOnCustomEventLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_readOnCustomEventLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind the OPC item to the TextBox or similar control as usually. 
        ///
        ///Then, use the &quot;Edit Live Bindings&quot; command on the control, and set the StringFormat property on the item binding as needed, using all standard .NET formatting capabilities. {0} in the formatting string represents the value to be formatted. For example, {0:F3} means a floating point value formatted with 3 decimal places..
        /// </summary>
        internal static string Form1_stringFormattingLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_stringFormattingLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the target control, use &quot;Bind to Point&quot; command and select the OPC item you want to bind to. 
        ///Then, use the &quot;Edit Live Bindings&quot; command, and for BindingOperations property, add a check next to the Write operation. In order to have the Write invoked when the control changes, set the WriteEventSource.SourceComponent to your control; the SourceMember of the WriteEventSource will be automatically determined, but you can change it, if you want to link to a different event. 
        ///
        ///Note: Some controls will require  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form1_subscribeAndWriteLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_subscribeAndWriteLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a PointBinder, edit the BindingGroups collection, &quot;Add&quot; a new binding group, set its AutoSubscribe property to False, and set its WriteEventSource.SourceComponent to the button that should invoke the Write. 
        ///
        ///On each of the value controls involved, use &quot;Bind to Point&quot; command and select the OPC item you want to write. Then, use the &quot;Edit Live Bindings&quot; command, and for the BindingOperations options, select only &quot;Write&quot;. Also, set the BindingGroup property of the item binding to the binding group you have [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form1_writeGroupLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_writeGroupLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a TextBox, use &quot;Bind to Point&quot; command and select the OPC item you want to write.
        /// 
        ///Then, use the &quot;Edit Live Bindings&quot; command, and for the BindingOperations options, select only &quot;Write&quot;. In order to have the Write invoked when the button is pressed, set the WriteEventSource.SourceComponent to the Button control; the SourceMember of the WriteEventSource will be automatically set to the Click event. This causes the Click on the button execute the Write operation, i.e. obtain the value from the control and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form1_writeSingleLinkLabel_LinkClicked_HelpText {
            get {
                return ResourceManager.GetString("Form1_writeSingleLinkLabel_LinkClicked_HelpText", resourceCulture);
            }
        }
    }
}
